# branches:
#   only:
#     - master

      # - clang-format

# script:
#   - source ./.travis/check-format.sh

stages:
  - format
  - documentation
  - deploy
jobs:
  include:
  - stage: format 
    addons:
      apt:
        packages:
          - clang-format
    script:
      - source ./.travis/check-format.sh

  - stage: documentation
    if: branch = "master" 
    addons:
      apt:
        packages:
          - doxygen
          - cmake
          - graphviz
    script:
      - source ./.travis/documentation.sh

  - stage: deploy
    if: branch = "master" 
    deploy:
      strategy: git
      provider: pages
      skip_cleanup: true
      local_dir: .docs/build/doc/html
      github_token: $GH_REPO_TOKEN
      on:
        branch: master
