branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - cmake
      - graphviz

script:
  - source ./.travis/documentation.sh

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  local_dir: .docs/build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
