git:
  depth: 1

addons:
  apt:
    packages:
      - doxygen
      - cmake
      - graphviz
      - clang-format

stages:
  - format
  - documentation
  - deploy
jobs:
  include:
  - stage: format
    script:
      - source ./.travis/check-format.sh

  - stage: documentation
    if: branch = "master" 
    script:
      - source ./.travis/documentation.sh

  - stage: deploy
    if: branch = "master" 
    deploy:
      strategy: git
      provider: pages
      skip_cleanup: true
      local_dir: .docs/build/doc/html
      github_token: $GH_REPO_TOKEN
      on:
        branch: master
