var annotated_dup =
[
    [ "robowflex", "namespacerobowflex.html", [
      [ "darts", "namespacerobowflex_1_1darts.html", [
        [ "ACM", "classrobowflex_1_1darts_1_1ACM.html", "classrobowflex_1_1darts_1_1ACM" ],
        [ "Viewer", "classrobowflex_1_1darts_1_1Viewer.html", "classrobowflex_1_1darts_1_1Viewer" ],
        [ "Window", "classrobowflex_1_1darts_1_1Window.html", "classrobowflex_1_1darts_1_1Window" ],
        [ "Widget", "classrobowflex_1_1darts_1_1Widget.html", "classrobowflex_1_1darts_1_1Widget" ],
        [ "ImGuiElement", "classrobowflex_1_1darts_1_1ImGuiElement.html", "classrobowflex_1_1darts_1_1ImGuiElement" ],
        [ "TextElement", "classrobowflex_1_1darts_1_1TextElement.html", "classrobowflex_1_1darts_1_1TextElement" ],
        [ "CheckboxElement", "classrobowflex_1_1darts_1_1CheckboxElement.html", "classrobowflex_1_1darts_1_1CheckboxElement" ],
        [ "ButtonElement", "classrobowflex_1_1darts_1_1ButtonElement.html", "classrobowflex_1_1darts_1_1ButtonElement" ],
        [ "RenderElement", "classrobowflex_1_1darts_1_1RenderElement.html", "classrobowflex_1_1darts_1_1RenderElement" ],
        [ "LinePlotElement", "classrobowflex_1_1darts_1_1LinePlotElement.html", "classrobowflex_1_1darts_1_1LinePlotElement" ],
        [ "WindowWidget", "classrobowflex_1_1darts_1_1WindowWidget.html", "classrobowflex_1_1darts_1_1WindowWidget" ],
        [ "TSREditWidget", "classrobowflex_1_1darts_1_1TSREditWidget.html", "classrobowflex_1_1darts_1_1TSREditWidget" ],
        [ "TSRSolveWidget", "classrobowflex_1_1darts_1_1TSRSolveWidget.html", "classrobowflex_1_1darts_1_1TSRSolveWidget" ],
        [ "Joint", "classrobowflex_1_1darts_1_1Joint.html", "classrobowflex_1_1darts_1_1Joint" ],
        [ "RnJoint", "classrobowflex_1_1darts_1_1RnJoint.html", "classrobowflex_1_1darts_1_1RnJoint" ],
        [ "SO2Joint", "classrobowflex_1_1darts_1_1SO2Joint.html", "classrobowflex_1_1darts_1_1SO2Joint" ],
        [ "SO3Joint", "classrobowflex_1_1darts_1_1SO3Joint.html", "classrobowflex_1_1darts_1_1SO3Joint" ],
        [ "DARTPlanner", "classrobowflex_1_1darts_1_1DARTPlanner.html", "classrobowflex_1_1darts_1_1DARTPlanner" ],
        [ "ConstraintExtractor", "classrobowflex_1_1darts_1_1ConstraintExtractor.html", "classrobowflex_1_1darts_1_1ConstraintExtractor" ],
        [ "TSRGoal", "classrobowflex_1_1darts_1_1TSRGoal.html", "classrobowflex_1_1darts_1_1TSRGoal" ],
        [ "JointRegionGoal", "classrobowflex_1_1darts_1_1JointRegionGoal.html", "classrobowflex_1_1darts_1_1JointRegionGoal" ],
        [ "PlanBuilder", "classrobowflex_1_1darts_1_1PlanBuilder.html", "classrobowflex_1_1darts_1_1PlanBuilder" ],
        [ "Robot", "classrobowflex_1_1darts_1_1Robot.html", "classrobowflex_1_1darts_1_1Robot" ],
        [ "StateSpace", "classrobowflex_1_1darts_1_1StateSpace.html", "classrobowflex_1_1darts_1_1StateSpace" ],
        [ "Structure", "classrobowflex_1_1darts_1_1Structure.html", "classrobowflex_1_1darts_1_1Structure" ],
        [ "TSR", "classrobowflex_1_1darts_1_1TSR.html", "classrobowflex_1_1darts_1_1TSR" ],
        [ "TSRSet", "classrobowflex_1_1darts_1_1TSRSet.html", "classrobowflex_1_1darts_1_1TSRSet" ],
        [ "TSRConstraint", "classrobowflex_1_1darts_1_1TSRConstraint.html", "classrobowflex_1_1darts_1_1TSRConstraint" ],
        [ "DistanceCollisionWrapper", "classrobowflex_1_1darts_1_1DistanceCollisionWrapper.html", "classrobowflex_1_1darts_1_1DistanceCollisionWrapper" ],
        [ "World", "classrobowflex_1_1darts_1_1World.html", "classrobowflex_1_1darts_1_1World" ]
      ] ],
      [ "IO", "namespacerobowflex_1_1IO.html", [
        [ "Bag", "classrobowflex_1_1IO_1_1Bag.html", "classrobowflex_1_1IO_1_1Bag" ],
        [ "RobotBroadcaster", "classrobowflex_1_1IO_1_1RobotBroadcaster.html", "classrobowflex_1_1IO_1_1RobotBroadcaster" ],
        [ "GNUPlotHelper", "classrobowflex_1_1IO_1_1GNUPlotHelper.html", "classrobowflex_1_1IO_1_1GNUPlotHelper" ],
        [ "GNUPlotPlanDataSetOutputter", "classrobowflex_1_1IO_1_1GNUPlotPlanDataSetOutputter.html", "classrobowflex_1_1IO_1_1GNUPlotPlanDataSetOutputter" ],
        [ "Handler", "classrobowflex_1_1IO_1_1Handler.html", "classrobowflex_1_1IO_1_1Handler" ],
        [ "HDF5Data", "classrobowflex_1_1IO_1_1HDF5Data.html", "classrobowflex_1_1IO_1_1HDF5Data" ],
        [ "HDF5File", "classrobowflex_1_1IO_1_1HDF5File.html", "classrobowflex_1_1IO_1_1HDF5File" ],
        [ "PluginManager", "classrobowflex_1_1IO_1_1PluginManager.html", "classrobowflex_1_1IO_1_1PluginManager" ],
        [ "RVIZHelper", "classrobowflex_1_1IO_1_1RVIZHelper.html", "classrobowflex_1_1IO_1_1RVIZHelper" ]
      ] ],
      [ "movegroup", "namespacerobowflex_1_1movegroup.html", [
        [ "MoveGroupHelper", "classrobowflex_1_1movegroup_1_1MoveGroupHelper.html", "classrobowflex_1_1movegroup_1_1MoveGroupHelper" ]
      ] ],
      [ "OMPL", "namespacerobowflex_1_1OMPL.html", [
        [ "Cob4OMPLPipelinePlanner", "classrobowflex_1_1OMPL_1_1Cob4OMPLPipelinePlanner.html", "classrobowflex_1_1OMPL_1_1Cob4OMPLPipelinePlanner" ],
        [ "FetchOMPLPipelinePlanner", "classrobowflex_1_1OMPL_1_1FetchOMPLPipelinePlanner.html", "classrobowflex_1_1OMPL_1_1FetchOMPLPipelinePlanner" ],
        [ "R2OMPLPipelinePlanner", "classrobowflex_1_1OMPL_1_1R2OMPLPipelinePlanner.html", "classrobowflex_1_1OMPL_1_1R2OMPLPipelinePlanner" ],
        [ "UR5OMPLPipelinePlanner", "classrobowflex_1_1OMPL_1_1UR5OMPLPipelinePlanner.html", "classrobowflex_1_1OMPL_1_1UR5OMPLPipelinePlanner" ],
        [ "Settings", "classrobowflex_1_1OMPL_1_1Settings.html", "classrobowflex_1_1OMPL_1_1Settings" ],
        [ "OMPLPipelinePlanner", "classrobowflex_1_1OMPL_1_1OMPLPipelinePlanner.html", "classrobowflex_1_1OMPL_1_1OMPLPipelinePlanner" ],
        [ "OMPLInterfacePlanner", "classrobowflex_1_1OMPL_1_1OMPLInterfacePlanner.html", "classrobowflex_1_1OMPL_1_1OMPLInterfacePlanner" ],
        [ "OMPLTrajectory", "classrobowflex_1_1OMPL_1_1OMPLTrajectory.html", "classrobowflex_1_1OMPL_1_1OMPLTrajectory" ]
      ] ],
      [ "opt", "namespacerobowflex_1_1opt.html", [
        [ "CHOMPSettings", "classrobowflex_1_1opt_1_1CHOMPSettings.html", "classrobowflex_1_1opt_1_1CHOMPSettings" ],
        [ "CHOMPPipelinePlanner", "classrobowflex_1_1opt_1_1CHOMPPipelinePlanner.html", "classrobowflex_1_1opt_1_1CHOMPPipelinePlanner" ],
        [ "TrajOptPipelinePlanner", "classrobowflex_1_1opt_1_1TrajOptPipelinePlanner.html", "classrobowflex_1_1opt_1_1TrajOptPipelinePlanner" ]
      ] ],
      [ "PlanningQuery", "structrobowflex_1_1PlanningQuery.html", "structrobowflex_1_1PlanningQuery" ],
      [ "PlanData", "classrobowflex_1_1PlanData.html", "classrobowflex_1_1PlanData" ],
      [ "PlanDataSet", "classrobowflex_1_1PlanDataSet.html", "classrobowflex_1_1PlanDataSet" ],
      [ "Profiler", "classrobowflex_1_1Profiler.html", "classrobowflex_1_1Profiler" ],
      [ "Experiment", "classrobowflex_1_1Experiment.html", "classrobowflex_1_1Experiment" ],
      [ "PlanDataSetOutputter", "classrobowflex_1_1PlanDataSetOutputter.html", "classrobowflex_1_1PlanDataSetOutputter" ],
      [ "JSONPlanDataSetOutputter", "classrobowflex_1_1JSONPlanDataSetOutputter.html", "classrobowflex_1_1JSONPlanDataSetOutputter" ],
      [ "TrajectoryPlanDataSetOutputter", "classrobowflex_1_1TrajectoryPlanDataSetOutputter.html", "classrobowflex_1_1TrajectoryPlanDataSetOutputter" ],
      [ "OMPLPlanDataSetOutputter", "classrobowflex_1_1OMPLPlanDataSetOutputter.html", "classrobowflex_1_1OMPLPlanDataSetOutputter" ],
      [ "MotionRequestBuilder", "classrobowflex_1_1MotionRequestBuilder.html", "classrobowflex_1_1MotionRequestBuilder" ],
      [ "Cob4Robot", "classrobowflex_1_1Cob4Robot.html", "classrobowflex_1_1Cob4Robot" ],
      [ "FetchRobot", "classrobowflex_1_1FetchRobot.html", "classrobowflex_1_1FetchRobot" ],
      [ "R2Robot", "classrobowflex_1_1R2Robot.html", "classrobowflex_1_1R2Robot" ],
      [ "UR5Robot", "classrobowflex_1_1UR5Robot.html", "classrobowflex_1_1UR5Robot" ],
      [ "Geometry", "classrobowflex_1_1Geometry.html", "classrobowflex_1_1Geometry" ],
      [ "ID", "classrobowflex_1_1ID.html", "classrobowflex_1_1ID" ],
      [ "Planner", "classrobowflex_1_1Planner.html", "classrobowflex_1_1Planner" ],
      [ "PoolPlanner", "classrobowflex_1_1PoolPlanner.html", "classrobowflex_1_1PoolPlanner" ],
      [ "SimpleCartesianPlanner", "classrobowflex_1_1SimpleCartesianPlanner.html", "classrobowflex_1_1SimpleCartesianPlanner" ],
      [ "PipelinePlanner", "classrobowflex_1_1PipelinePlanner.html", "classrobowflex_1_1PipelinePlanner" ],
      [ "Pool", "classrobowflex_1_1Pool.html", "classrobowflex_1_1Pool" ],
      [ "Robot", "classrobowflex_1_1Robot.html", "classrobowflex_1_1Robot" ],
      [ "ParamRobot", "classrobowflex_1_1ParamRobot.html", "classrobowflex_1_1ParamRobot" ],
      [ "Scene", "classrobowflex_1_1Scene.html", "classrobowflex_1_1Scene" ],
      [ "Trajectory", "classrobowflex_1_1Trajectory.html", "classrobowflex_1_1Trajectory" ],
      [ "Exception", "classrobowflex_1_1Exception.html", "classrobowflex_1_1Exception" ],
      [ "ROS", "classrobowflex_1_1ROS.html", "classrobowflex_1_1ROS" ],
      [ "TrajOptPlanner", "classrobowflex_1_1TrajOptPlanner.html", "classrobowflex_1_1TrajOptPlanner" ]
    ] ],
    [ "robowflex_visualization", "namespacerobowflex__visualization.html", [
      [ "robot", "namespacerobowflex__visualization_1_1robot.html", [
        [ "Robot", "classrobowflex__visualization_1_1robot_1_1Robot.html", "classrobowflex__visualization_1_1robot_1_1Robot" ]
      ] ],
      [ "scene", "namespacerobowflex__visualization_1_1scene.html", [
        [ "Scene", "classrobowflex__visualization_1_1scene_1_1Scene.html", "classrobowflex__visualization_1_1scene_1_1Scene" ]
      ] ]
    ] ],
    [ "CustomTrajOptPlanner", "classCustomTrajOptPlanner.html", "classCustomTrajOptPlanner" ],
    [ "CHOMPPipelinePlannerConstPtr", "classrobowflex_1_1CHOMP_1_1CHOMPPipelinePlannerConstPtr.html", null ],
    [ "CHOMPPipelinePlannerPtr", "classrobowflex_1_1CHOMP_1_1CHOMPPipelinePlannerPtr.html", null ],
    [ "Cob4RobotConstPtr", "classrobowflex_1_1Cob4RobotConstPtr.html", null ],
    [ "Cob4RobotPtr", "classrobowflex_1_1Cob4RobotPtr.html", null ],
    [ "ACMConstPtr", "classrobowflex_1_1darts_1_1ACMConstPtr.html", null ],
    [ "ACMPtr", "classrobowflex_1_1darts_1_1ACMPtr.html", null ],
    [ "DARTPlannerConstPtr", "classrobowflex_1_1darts_1_1DARTPlannerConstPtr.html", null ],
    [ "DARTPlannerPtr", "classrobowflex_1_1darts_1_1DARTPlannerPtr.html", null ],
    [ "ImGuiElementConstPtr", "classrobowflex_1_1darts_1_1ImGuiElementConstPtr.html", null ],
    [ "ImGuiElementPtr", "classrobowflex_1_1darts_1_1ImGuiElementPtr.html", null ],
    [ "JointConstPtr", "classrobowflex_1_1darts_1_1JointConstPtr.html", null ],
    [ "JointPtr", "classrobowflex_1_1darts_1_1JointPtr.html", null ],
    [ "JointRegionGoalConstPtr", "classrobowflex_1_1darts_1_1JointRegionGoalConstPtr.html", null ],
    [ "JointRegionGoalPtr", "classrobowflex_1_1darts_1_1JointRegionGoalPtr.html", null ],
    [ "PlanBuilderConstPtr", "classrobowflex_1_1darts_1_1PlanBuilderConstPtr.html", null ],
    [ "PlanBuilderPtr", "classrobowflex_1_1darts_1_1PlanBuilderPtr.html", null ],
    [ "StateSamplerConstPtr", "classrobowflex_1_1darts_1_1StateSpace_1_1StateSamplerConstPtr.html", null ],
    [ "StateSamplerPtr", "classrobowflex_1_1darts_1_1StateSpace_1_1StateSamplerPtr.html", null ],
    [ "StateSpaceConstPtr", "classrobowflex_1_1darts_1_1StateSpaceConstPtr.html", null ],
    [ "StateSpacePtr", "classrobowflex_1_1darts_1_1StateSpacePtr.html", null ],
    [ "StructureConstPtr", "classrobowflex_1_1darts_1_1StructureConstPtr.html", null ],
    [ "StructurePtr", "classrobowflex_1_1darts_1_1StructurePtr.html", null ],
    [ "TSRConstPtr", "classrobowflex_1_1darts_1_1TSRConstPtr.html", null ],
    [ "TSRConstraintConstPtr", "classrobowflex_1_1darts_1_1TSRConstraintConstPtr.html", null ],
    [ "TSRConstraintPtr", "classrobowflex_1_1darts_1_1TSRConstraintPtr.html", null ],
    [ "TSRGoalConstPtr", "classrobowflex_1_1darts_1_1TSRGoalConstPtr.html", null ],
    [ "TSRGoalPtr", "classrobowflex_1_1darts_1_1TSRGoalPtr.html", null ],
    [ "TSRPtr", "classrobowflex_1_1darts_1_1TSRPtr.html", null ],
    [ "TSRSetConstPtr", "classrobowflex_1_1darts_1_1TSRSetConstPtr.html", null ],
    [ "TSRSetPtr", "classrobowflex_1_1darts_1_1TSRSetPtr.html", null ],
    [ "WindowConstPtr", "classrobowflex_1_1darts_1_1WindowConstPtr.html", null ],
    [ "WindowPtr", "classrobowflex_1_1darts_1_1WindowPtr.html", null ],
    [ "WindowWidgetConstPtr", "classrobowflex_1_1darts_1_1WindowWidgetConstPtr.html", null ],
    [ "WindowWidgetPtr", "classrobowflex_1_1darts_1_1WindowWidgetPtr.html", null ],
    [ "WorldConstPtr", "classrobowflex_1_1darts_1_1WorldConstPtr.html", null ],
    [ "WorldPtr", "classrobowflex_1_1darts_1_1WorldPtr.html", null ],
    [ "ExperimentConstPtr", "classrobowflex_1_1ExperimentConstPtr.html", null ],
    [ "ExperimentPtr", "classrobowflex_1_1ExperimentPtr.html", null ],
    [ "FetchRobotConstPtr", "classrobowflex_1_1FetchRobotConstPtr.html", null ],
    [ "FetchRobotPtr", "classrobowflex_1_1FetchRobotPtr.html", null ],
    [ "GeometryConstPtr", "classrobowflex_1_1GeometryConstPtr.html", null ],
    [ "GeometryPtr", "classrobowflex_1_1GeometryPtr.html", null ],
    [ "HDF5DataConstPtr", "classrobowflex_1_1HDF5DataConstPtr.html", null ],
    [ "HDF5DataPtr", "classrobowflex_1_1HDF5DataPtr.html", null ],
    [ "IDConstPtr", "classrobowflex_1_1IDConstPtr.html", null ],
    [ "IDPtr", "classrobowflex_1_1IDPtr.html", null ],
    [ "RVIZHelperConstPtr", "classrobowflex_1_1IO_1_1RVIZHelperConstPtr.html", null ],
    [ "RVIZHelperPtr", "classrobowflex_1_1IO_1_1RVIZHelperPtr.html", null ],
    [ "MotionRequestBuilderConstPtr", "classrobowflex_1_1MotionRequestBuilderConstPtr.html", null ],
    [ "MotionRequestBuilderPtr", "classrobowflex_1_1MotionRequestBuilderPtr.html", null ],
    [ "Cob4OMPLPipelinePlannerConstPtr", "classrobowflex_1_1OMPL_1_1Cob4OMPLPipelinePlannerConstPtr.html", null ],
    [ "Cob4OMPLPipelinePlannerPtr", "classrobowflex_1_1OMPL_1_1Cob4OMPLPipelinePlannerPtr.html", null ],
    [ "FetchOMPLPipelinePlannerConstPtr", "classrobowflex_1_1OMPL_1_1FetchOMPLPipelinePlannerConstPtr.html", null ],
    [ "FetchOMPLPipelinePlannerPtr", "classrobowflex_1_1OMPL_1_1FetchOMPLPipelinePlannerPtr.html", null ],
    [ "OMPLInterfacePlannerConstPtr", "classrobowflex_1_1OMPL_1_1OMPLInterfacePlannerConstPtr.html", null ],
    [ "OMPLInterfacePlannerPtr", "classrobowflex_1_1OMPL_1_1OMPLInterfacePlannerPtr.html", null ],
    [ "OMPLPipelinePlannerConstPtr", "classrobowflex_1_1OMPL_1_1OMPLPipelinePlannerConstPtr.html", null ],
    [ "OMPLPipelinePlannerPtr", "classrobowflex_1_1OMPL_1_1OMPLPipelinePlannerPtr.html", null ],
    [ "OMPLTrajectoryConstPtr", "classrobowflex_1_1OMPL_1_1OMPLTrajectoryConstPtr.html", null ],
    [ "OMPLTrajectoryPtr", "classrobowflex_1_1OMPL_1_1OMPLTrajectoryPtr.html", null ],
    [ "R2OMPLPipelinePlannerConstPtr", "classrobowflex_1_1OMPL_1_1R2OMPLPipelinePlannerConstPtr.html", null ],
    [ "R2OMPLPipelinePlannerPtr", "classrobowflex_1_1OMPL_1_1R2OMPLPipelinePlannerPtr.html", null ],
    [ "UR5OMPLPipelinePlannerConstPtr", "classrobowflex_1_1OMPL_1_1UR5OMPLPipelinePlannerConstPtr.html", null ],
    [ "UR5OMPLPipelinePlannerPtr", "classrobowflex_1_1OMPL_1_1UR5OMPLPipelinePlannerPtr.html", null ],
    [ "TrajOptPipelinePlannerConstPtr", "classrobowflex_1_1opt_1_1TrajOptPipelinePlannerConstPtr.html", null ],
    [ "TrajOptPipelinePlannerPtr", "classrobowflex_1_1opt_1_1TrajOptPipelinePlannerPtr.html", null ],
    [ "ParamRobotConstPtr", "classrobowflex_1_1ParamRobotConstPtr.html", null ],
    [ "ParamRobotPtr", "classrobowflex_1_1ParamRobotPtr.html", null ],
    [ "PipelinePlannerConstPtr", "classrobowflex_1_1PipelinePlannerConstPtr.html", null ],
    [ "PipelinePlannerPtr", "classrobowflex_1_1PipelinePlannerPtr.html", null ],
    [ "PlanDataConstPtr", "classrobowflex_1_1PlanDataConstPtr.html", null ],
    [ "PlanDataPtr", "classrobowflex_1_1PlanDataPtr.html", null ],
    [ "PlanDataSetConstPtr", "classrobowflex_1_1PlanDataSetConstPtr.html", null ],
    [ "PlanDataSetPtr", "classrobowflex_1_1PlanDataSetPtr.html", null ],
    [ "PlannerConstPtr", "classrobowflex_1_1PlannerConstPtr.html", null ],
    [ "PlannerPtr", "classrobowflex_1_1PlannerPtr.html", null ],
    [ "ProfilerConstPtr", "classrobowflex_1_1ProfilerConstPtr.html", null ],
    [ "ProfilerPtr", "classrobowflex_1_1ProfilerPtr.html", null ],
    [ "R2RobotConstPtr", "classrobowflex_1_1R2RobotConstPtr.html", null ],
    [ "R2RobotPtr", "classrobowflex_1_1R2RobotPtr.html", null ],
    [ "RobotConstPtr", "classrobowflex_1_1RobotConstPtr.html", null ],
    [ "RobotPtr", "classrobowflex_1_1RobotPtr.html", null ],
    [ "SceneConstPtr", "classrobowflex_1_1SceneConstPtr.html", null ],
    [ "ScenePtr", "classrobowflex_1_1ScenePtr.html", null ],
    [ "SimpleCartesianPlannerConstPtr", "classrobowflex_1_1SimpleCartesianPlannerConstPtr.html", null ],
    [ "SimpleCartesianPlannerPtr", "classrobowflex_1_1SimpleCartesianPlannerPtr.html", null ],
    [ "TrajectoryConstPtr", "classrobowflex_1_1TrajectoryConstPtr.html", null ],
    [ "TrajectoryPtr", "classrobowflex_1_1TrajectoryPtr.html", null ],
    [ "TrajOptPlannerConstPtr", "classrobowflex_1_1TrajOptPlannerConstPtr.html", null ],
    [ "TrajOptPlannerPtr", "classrobowflex_1_1TrajOptPlannerPtr.html", null ],
    [ "UR5RobotConstPtr", "classrobowflex_1_1UR5RobotConstPtr.html", null ],
    [ "UR5RobotPtr", "classrobowflex_1_1UR5RobotPtr.html", null ]
];