camera:
  pose:
    position: [8.59542, -6.71317, 5.36197]
    orientation: [0.462, 0.191, 0.331, 0.800]
  lens: 9.2
light_settings:
  use_environment_light: True
  environment_energy: 1.5
  use_ambient_occlusion: True
  ao_factor: 1 
  samples: 15
