base_pose: [0.85, 0, 0]
base_var: [0.0, 0.0, 0.0]
cans_var: [0.0, 0.0, 0]
end: 5
interactive: true
moveit_planning_group: arm
num_threads: 3
ompl_config_file: /home/carlos/ros/melodic/system/src/fetch_moveit_config/config/ompl_planning.yaml
pick_cans: [Can1]
pick_grasp: Can Side Grasp
pick_indexes: [0]
place_grasp: Shelf Top Loc
place_indexes: [0]
place_objects: []
planning_time: 10
save_folder: table/new
save_octomap: false
start: 1
