name: Build Indigo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-indigo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Compile Docker Container
      run: ./.docker/indigo/build-indigo.sh

    - name: Clean Docker
      run: sudo ./.ci/clean-docker.sh
