name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download Dependencies
      run: sudo apt-get install doxygen graphviz cmake        

    - name: Build Documentation
      run: source $GITHUB_WORKSPACE/.ci/documentation.sh

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.0
      with:
         build_dir: $GITHUB_WORKSPACE/.docs/build/doc/html
         jekyll: false
