name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linting:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Download Dependencies
      run: sudo apt-get install clang-format
    - name: Check Formatting
      run: source ./.ci/check-format.sh
       
  documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download Dependencies
      run: sudo apt-get install doxygen graphviz cmake        

    - name: Build Documentation
      run: source ./.ci/documentation.sh

    - name: GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./.docs/build/doc/html
